# Generated by Django 5.1.2 on 2024-11-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_city_member_password_member_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='LastName',
        ),
    ]
