# Generated by Django 5.1.2 on 2024-11-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_firstname_member_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Password',
            field=models.BinaryField(max_length=255),
        ),
    ]
