# Generated by Django 5.1.2 on 2024-11-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
