# Generated by Django 5.1.2 on 2024-11-18 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='encrypted_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
