# Generated by Django 5.1.2 on 2024-11-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_encrypted_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='encrypted_password',
        ),
    ]
