# Generated by Django 5.1.2 on 2024-12-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_member_encrypted_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Password',
            field=models.TextField(max_length=4000),
        ),
    ]
