# Generated by Django 5.1.2 on 2024-12-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Password',
            field=models.CharField(max_length=4000),
        ),
    ]
