# Generated by Django 5.1.2 on 2024-12-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
