# Generated by Django 5.1.2 on 2024-12-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_delete_userdata_member_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='member',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
