# Generated by Django 5.1.2 on 2024-12-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
