# Generated by Django 5.1.2 on 2024-12-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_member_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_login',
        ),
    ]
