# Generated by Django 5.1.2 on 2024-12-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
    ]
